default_border pixel 3

# Pywal dynamic colors
set_from_resource $bg       background #000000
set_from_resource $fg       foreground #ffffff
set_from_resource $color0   color0 #000000
set_from_resource $color1   color1 #000000
set_from_resource $color2   color2 #000000
set_from_resource $color3   color3 #000000
set_from_resource $color4   color4 #000000
set_from_resource $color5   color5 #000000
set_from_resource $color6   color6 #000000
set_from_resource $color7   color7 #000000
set_from_resource $color8   color8 #000000
set_from_resource $color9   color9 #000000
set_from_resource $color10  color10 #000000
set_from_resource $color11  color11 #000000
set_from_resource $color12  color12 #000000
set_from_resource $color13  color13 #000000
set_from_resource $color14  color14 #000000
set_from_resource $color15  color15 #000000

# applies colors
# i3 color structure is as follows:
#
# 			<border><bg><text><indicator><child-border>
client.focused          $color4 $bg $fg $color6 $color4
#client.focused_inactive $color5 $bg $fg $color7 $color5
client.unfocused        $color0 $bg $fg $color9 $color0
#client.urgent           $color1 $bg $fg $color3 $color1
#
#client.focused          #89b4fa $bg $fg #94e2d5
#client.focused_inactive #cba6f7 $bg $fg #6c7086
#client.unfocused        #6c7086 $bg $fg #1e1e2e
#client.urgent           #f28fad $bg $fg #f9e2af
