backend = "glx";
vsync = true;

shadow = false;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

rounded-corners = false;

inactive-dim = 0.0;

inactive-opacity = 0.85;
inactive-opacity-override = false;

opacity-rule = [
   "100:class_g = 'librewolf'",
   "90:class_g = 'Alacritty'",
   "90:class_g = 'URxvt'"
];

opacity-exclude = [
   "class_g = 'librewolf'"
];

fade-exclude = [
  "class_g = 'librewolf'"
];

wintypes = {
   menu = {  }
   dropdown_menu = {  }
   popup_menu = {  }
   utility = {  }
};
